import json
import os
import sys
from datetime import datetime
from pathlib import Path

import requests
from playwright.sync_api import sync_playwright


CONFIG_FILE = "config.json"
STATE_FILE = "state.json"

APPLE_SITE = "https://www.apple.com/hk-zh"
APPLE_BUY_URL = "https://www.apple.com/hk/shop/buy-iphone"

TELEGRAM_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID")


def load_config():
    with open(CONFIG_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def load_state():
    if not Path(STATE_FILE).exists():
        return {"alerted": {}}

    try:
        with open(STATE_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {"alerted": {}}


def save_state(state):
    with open(STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(
            state,
            f,
            ensure_ascii=False,
            indent=2
        )


def send_telegram(message):
    if not TELEGRAM_TOKEN:
        raise RuntimeError(
            "TELEGRAM_BOT_TOKEN is missing"
        )

    if not TELEGRAM_CHAT_ID:
        raise RuntimeError(
            "TELEGRAM_CHAT_ID is missing"
        )

    url = (
        f"https://api.telegram.org/"
        f"bot{TELEGRAM_TOKEN}/sendMessage"
    )

    response = requests.post(
        url,
        json={
            "chat_id": TELEGRAM_CHAT_ID,
            "text": message
        },
        timeout=20
    )

    response.raise_for_status()

    print("✅ Telegram notification sent.")


def get_store_name(store):
    return (
        store.get("storeName")
        or store.get("name")
        or store.get("storeNumber")
        or "Unknown Store"
    )


def is_available_today(part):
    if not isinstance(part, dict):
        return False

    pickup_display = str(
        part.get("pickupDisplay", "")
    ).lower()

    eligible = (
        part.get("storePickEligible")
        is True
    )

    quote = str(
        part.get("storePickupQuote", "")
    ).lower()

    pickup_message = str(
        part.get("pickupMessage", "")
    ).lower()

    text = (
        quote
        + " "
        + pickup_message
    )

    today = (
        "today" in text
        or "今日" in text
        or "今天" in text
    )

    return (
        pickup_display == "available"
        and eligible
        and today
    )


def get_pickup_data(page, part_number):
    print()
    print("=" * 70)
    print("Opening Apple Hong Kong Store...")
    print("=" * 70)

    page.goto(
        APPLE_BUY_URL,
        wait_until="domcontentloaded",
        timeout=60000
    )

    page.wait_for_timeout(5000)

    print(
        "Apple page loaded."
    )

    # The page itself makes the pickup request.
    # Capture the response generated by Apple.
    response_data = None

    def handle_response(response):
        nonlocal response_data

        url = response.url

        if (
            "pickup-message" in url
            and response.status == 200
        ):
            try:
                data = response.json()

                if (
                    isinstance(data, dict)
                    and "body" in data
                ):
                    response_data = data

                    print()
                    print(
                        "✅ Captured Apple "
                        "pickup-message response."
                    )

            except Exception:
                pass

    page.on(
        "response",
        handle_response
    )

    # Reload after response listener is installed.
    page.reload(
        wait_until="domcontentloaded",
        timeout=60000
    )

    page.wait_for_timeout(8000)

    if response_data is None:
        print()
        print(
            "❌ Could not capture "
            "pickup-message response."
        )

        return None

    return response_data


def extract_stores(data):
    body = data.get(
        "body",
        {}
    )

    stores = body.get(
        "stores",
        []
    )

    if not isinstance(
        stores,
        list
    ):
        return []

    return stores


def check_stock(config):
    products = config.get(
        "products",
        []
    )

    if not products:
        raise RuntimeError(
            "No products configured."
        )

    product = products[0]

    part_number = product[
        "part_number"
    ]

    print(
        f"Product: {part_number}"
    )

    with sync_playwright() as p:

        browser = p.chromium.launch(
            headless=True
        )

        context = browser.new_context(
            locale="zh-HK",
            timezone_id="Asia/Hong_Kong",
            user_agent=(
                "Mozilla/5.0 "
                "(Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 "
                "(KHTML, like Gecko) "
                "Chrome/140.0.0.0 "
                "Safari/537.36"
            )
        )

        page = context.new_page()

        data = get_pickup_data(
            page,
            part_number
        )

        browser.close()

    if data is None:
        return None

    stores = extract_stores(
        data
    )

    print()
    print(
        f"Apple returned "
        f"{len(stores)} store(s)."
    )

    matches = []

    for store in stores:

        store_name = get_store_name(
            store
        )

        store_number = store.get(
            "storeNumber",
            "UNKNOWN"
        )

        availability = store.get(
            "partsAvailability",
            {}
        )

        part = availability.get(
            part_number,
            {}
        )

        available = (
            is_available_today(
                part
            )
        )

        print()
        print(
            f"🏪 {store_name} "
            f"({store_number})"
        )

        print(
            "   pickupDisplay:",
            part.get(
                "pickupDisplay",
                "unknown"
            )
        )

        print(
            "   storePickEligible:",
            part.get(
                "storePickEligible",
                False
            )
        )

        print(
            "   storePickupQuote:",
            part.get(
                "storePickupQuote",
                ""
            )
        )

        print(
            "   TODAY AVAILABLE:",
            available
        )

        if available:

            matches.append({
                "store_name": store_name,
                "store_number": store_number,
                "product_name": product[
                    "name"
                ],
                "part_number": part_number,
                "pickup_quote": part.get(
                    "storePickupQuote",
                    "今日"
                ),
                "product_url": product.get(
                    "product_url",
                    APPLE_BUY_URL
                )
            })

    return matches


def build_message(matches):

    now = datetime.now().strftime(
        "%H:%M:%S"
    )

    lines = [
        f"🚨📱 Apple Store 有貨 {now}",
        ""
    ]

    for item in matches:

        lines.append(
            f"• {item['product_name']} — "
            f"{item['store_name']}"
        )

        lines.append(
            f"  備妥於："
            f"{item['pickup_quote']}"
        )

        lines.append("")

    lines.append(
        "🔗 "
        + matches[0]["product_url"]
    )

    return "\n".join(lines)


def main():

    config = load_config()

    test_mode = (
        os.environ.get(
            "TEST_STOCK",
            "false"
        ).lower()
        == "true"
    )

    if test_mode:

        print(
            "🧪 TEST_STOCK=true"
        )

        fake = {
            "pickupDisplay": "available",
            "storePickEligible": True,
            "storePickupQuote": "Today"
        }

        if is_available_today(fake):

            send_telegram(
                "🚨📱 TEST — iPhone 18 Pro 有貨\n\n"
                "• 512GB 冰川色 — TEST Apple Store\n"
                "  備妥於：今日\n\n"
                "⚠️ 測試通知，並非真實庫存。"
            )

        return

    matches = check_stock(
        config
    )

    if matches is None:

        print(
            "❌ Inventory check failed."
        )

        print(
            "No stock conclusion was made."
        )

        sys.exit(1)

    if not matches:

        print()
        print(
            "No matching today-pickup "
            "stock found."
        )

        return

    message = build_message(
        matches
    )

    print()
    print(message)

    send_telegram(
        message
    )


if __name__ == "__main__":
    main()
